include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  # Allowed for local debugging/logs as requested
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_string_interpolations: true
    avoid_unnecessary_containers: true
