import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';

import '../core/constants/app_constants.dart';
import '../features/chat/domain/models/chat_session.dart';
import '../features/chat/domain/models/chat_message.dart';
import '../features/chat/domain/models/system_prompt.dart';
import '../core/constants/system_prompt_presets.dart';

class StorageService {
  late Box<ChatSession> _chatBox;
  late Box<SystemPrompt> _systemPromptBox;
  late Box _settingsBox;

  Future<void> init() async {
    await Hive.initFlutter();

    // Adapters will be generated by build_runner
    Hive.registerAdapter(ChatMessageAdapter());
    Hive.registerAdapter(ChatSessionAdapter());
    Hive.registerAdapter(SystemPromptAdapter());

    _chatBox = await Hive.openBox<ChatSession>(AppConstants.chatBoxName);
    _systemPromptBox = await Hive.openBox<SystemPrompt>(
      AppConstants.systemPromptsBoxName,
    );
    _settingsBox = await Hive.openBox(AppConstants.settingsBoxName);

    // Seed system prompts if empty
    if (_systemPromptBox.isEmpty) {
      final initialPrompts = SystemPromptPresets.getInitialPrompts();
      for (final prompt in initialPrompts) {
        await _systemPromptBox.put(prompt.id, prompt);
      }
    }
  }

  ValueListenable<Box<ChatSession>> get chatBoxListenable =>
      _chatBox.listenable();

  // Chats
  List<ChatSession> getChatSessions() {
    return _chatBox.values.toList()
      ..sort((a, b) => b.createdAt.compareTo(a.createdAt));
  }

  Future<void> saveChatSession(ChatSession session) async {
    await _chatBox.put(session.id, session);
  }

  Future<void> deleteChatSession(String id) async {
    await _chatBox.delete(id);
  }

  Future<void> clearAllChats() async {
    await _chatBox.clear();
  }

  ChatSession? getChatSession(String id) {
    return _chatBox.get(id);
  }

  // System Prompts
  ValueListenable<Box<SystemPrompt>> get promptBoxListenable =>
      _systemPromptBox.listenable();

  List<SystemPrompt> getSystemPrompts() {
    return _systemPromptBox.values.toList();
  }

  Future<void> saveSystemPrompt(SystemPrompt prompt) async {
    await _systemPromptBox.put(prompt.id, prompt);
  }

  Future<void> deleteSystemPrompt(String id) async {
    await _systemPromptBox.delete(id);
  }

  // Settings
  Future<void> saveSetting(String key, dynamic value) async {
    await _settingsBox.put(key, value);
  }

  dynamic getSetting(String key, {dynamic defaultValue}) {
    return _settingsBox.get(key, defaultValue: defaultValue);
  }
}
