// Mocks generated by Mockito 5.4.4 from annotations
// in pocketllm_lite/test/features/settings/presentation/widgets/model_download_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:pocketllm_lite/features/chat/domain/models/ollama_model.dart'
    as _i4;
import 'package:pocketllm_lite/features/chat/domain/models/pull_progress.dart'
    as _i5;
import 'package:pocketllm_lite/services/ollama_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OllamaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOllamaService extends _i1.Mock implements _i2.OllamaService {
  @override
  void updateBaseUrl(String? url) => super.noSuchMethod(
    Invocation.method(#updateBaseUrl, [url]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> checkConnection() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnection, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.OllamaModel>> listModels() =>
      (super.noSuchMethod(
            Invocation.method(#listModels, []),
            returnValue: _i3.Future<List<_i4.OllamaModel>>.value(
              <_i4.OllamaModel>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.OllamaModel>>.value(
              <_i4.OllamaModel>[],
            ),
          )
          as _i3.Future<List<_i4.OllamaModel>>);

  @override
  _i3.Stream<String> generateChatStream(
    String? model,
    List<Map<String, dynamic>>? messages, {
    Map<String, dynamic>? options,
    String? system,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateChatStream,
              [model, messages],
              {#options: options, #system: system},
            ),
            returnValue: _i3.Stream<String>.empty(),
            returnValueForMissingStub: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i3.Stream<_i5.PullProgress> pullModel(String? modelName) =>
      (super.noSuchMethod(
            Invocation.method(#pullModel, [modelName]),
            returnValue: _i3.Stream<_i5.PullProgress>.empty(),
            returnValueForMissingStub: _i3.Stream<_i5.PullProgress>.empty(),
          )
          as _i3.Stream<_i5.PullProgress>);

  @override
  _i3.Future<void> deleteModel(String? modelName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteModel, [modelName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> enhancePrompt({
    required String? model,
    required String? userInput,
    required String? systemPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enhancePrompt, [], {
              #model: model,
              #userInput: userInput,
              #systemPrompt: systemPrompt,
            }),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#enhancePrompt, [], {
                  #model: model,
                  #userInput: userInput,
                  #systemPrompt: systemPrompt,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#enhancePrompt, [], {
                  #model: model,
                  #userInput: userInput,
                  #systemPrompt: systemPrompt,
                }),
              ),
            ),
          )
          as _i3.Future<String>);
}
